# Generated by Django 5.0.1 on 2025-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_options_file_description_file_filesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filesize',
            field=models.BigIntegerField(default=0),
        ),
    ]
