# Generated by Django 5.0.1 on 2025-11-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_anomaly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='event',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
