# Generated by Django 5.0.1 on 2025-12-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_anomaly', '0003_useractivity_delete_anomalylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at']},
        ),
    ]
